### ISSUE TITLE
Request: publish latest stable version to pip

### ISSUE THREAD

**Issue by kyoka** [Polyconseil/django-cid#32]
Hello,

I am installing django-cid with pip, latest version available is 0.2.0 and it's missing this fix

https://github.com/Polyconseil/django-cid/issues/16

Is there a plan to publish newer version to pip soon?

Thanks!

**Comment by dbaty** [comment]
Hi,

We (Polyconseil) have taken over the maintenance. I am almost ready to release a new version that will include the fix you mention. I just need access to the ReadTheDocs account, which is out-of-sync since the GitHub repository has been moved. Unfortunately, it is taking more time than I thought.

You may expect a release within a week.

**Comment by dbaty** [comment]
Hi @kyoka. I have finally gained access to the ReadTheDocs account and after some fumbling around, have manage to cut 2 new releases.

**WARNING:** it has backward incompatible changes. Be sure to read the highlighted notes of the 1.0 release at https://django-correlation-id.readthedocs.io/en/latest/history.html#id2.
